### ISSUE TITLE
[Util Suggestion]: Ram Calculator!

### ISSUE THREAD

**Issue by Dawsson** [flytegg/mc-utils#182]
### Description

Calculates ram needs for input. world size, players, folia/paper, plugin count, etc

**Comment by Savya-lol** [comment]
similar to bisect's? Would be inaccurate but nice
![image](https://github.com/flytegg/mcu-website/assets/54802693/8b03d23c-e87a-4b6e-a59c-1af73482b057)

**Comment by ShadowThijs** [comment]
Two mockups I made show what I had in mind for this Ram Calculator

![Ram Calc Mockup 1](https://github.com/flytegg/mc-utils/assets/62294249/96b42ba8-45e5-47ac-80a7-d1741ef26076)
![Ram Calc Mockup 2](https://github.com/flytegg/mc-utils/assets/62294249/c5d9ba41-7305-4b3c-a60b-d290f4302311)

**Comment by stephendotgg** [comment]
@ShadowThijs This is awesome! Thanks a lot for putting in the effort. If you want to make it, please go ahead!

Perhaps we could find a way to give the user a nudge to the Start File Generator after calculating the ram (and vice versa?).

**Comment by ShadowThijs** [comment]
A simple version has been made with some mockup GB size for the amount of players and mods/modpack size. (Trying to merge but forgot to pull/fetch, so I am having an aneurism) 
I will try to add the Start File Generator now.

**Comment by ShadowThijs** [comment]
I the user can now press a button on the ram calculator page to go to the start file generator and is able to change the ram amount on there with the ram value from the calculator.
The button on both pages are a bit wonky in my opinion so they are subject to change (styles and position)

![image](https://github.com/flytegg/mc-utils/assets/62294249/8508b4c0-92ca-41d4-8c5f-270d54a6b11e)
![image](https://github.com/flytegg/mc-utils/assets/62294249/ae4263cb-d45a-4fab-8fe9-785d4ff335f4)
