### ISSUE TITLE
[Util Suggestion]: new features to the 'Color Text Generator'

### ISSUE THREAD

**Issue by MiresPL** [flytegg/mc-utils#185]
### Description

It would be nice to be able to see how the colored text would look on item (item name, lore)/kick screen 

### Extra Info

...

**Comment by stephendotgg** [comment]
Sure

**Comment by stephendotgg** [comment]
Done, can be seen through redesign branch, will be merged to master soon. Thanks for the issue!

**Comment by stephendotgg** [comment]
![image](https://github.com/flytegg/mc-utils/assets/138625055/6bb655f0-62e1-42ef-aa9a-aec19d77b1b6)
![image](https://github.com/flytegg/mc-utils/assets/138625055/f455e52d-c077-424f-a317-0d58bdff93f8)
![image](https://github.com/flytegg/mc-utils/assets/138625055/7e28bec5-fd88-451a-84ed-f010cd4f129f)
