### ISSUE TITLE
[Util Change]: Server jars Fabric release date bug

### ISSUE THREAD

**Issue by stephendotgg** [flytegg/mc-utils#193]
### Util Name

Server Jars

### Changes

![image](https://github.com/flytegg/mc-utils/assets/138625055/4df09fe8-85ba-4a6e-883d-1f62beaa67fe)

**Comment by StillLutto** [comment]
After looking a bit at it, it is a apparent that it's a problem with the fabric API itself. I will see if I can inform them. There might need to be a workaround for this though.

**Comment by joshbker** [comment]
I think the issue is we're just pulling the wrong release date - maybe from the installer or loader (rather than the game version's release date), as I assume they regularly update those.

**Comment by StillLutto** [comment]
@joshbker For this I would say that the release date that we need to pull would be the fabric loader release date right? If so, the v2 fabric meta does not store this. I suggest taking a workaround such a stating "Release date not accessible" or just removing the release date column all together.

**Comment by stephendotgg** [comment]
Agree with above, doesn't appear to be possible to pull this release date from the data the Fabric API gives us.

Here's a (formatted) snippet of a JSON response: 
https://paste.learnspigot.com/ilibokisaw.bash

Both the timestamps represent the same date and time, always being very close to the current date/time. Therefore these data points are worthless.

Therefore, it doesn't look like they expose this data. Perhaps something we should nag them on. But nothing we can do from here for this issue.

Closing and adding a note on the site regarding this.
