### ISSUE TITLE
[Bug Fix]: Small text converter 

### ISSUE THREAD

**Issue by MatteoFreschiDev** [flytegg/mc-utils#199]
### Util Name

Font is incorrect

### Changes

The font used for small text is changed and doesn't work on minecraft anymore, please bring back the old one.

**Comment by joshbker** [comment]
Hey, we're aware that this currently looks broken on the website, but the actual text should still work in game if you copy it - it is for us, are you able to provide any evidence/how to reproduce? We'll be fixing this shortly though in #191

**Comment by stephendotgg** [comment]
Closing as no response + can't reproduce
