### ISSUE TITLE
[Util Change]: Color codes table got missed in styling redesign

### ISSUE THREAD

**Issue by stephendotgg** [flytegg/mc-utils#201]
### Util Name

Color Codes

### Changes

![image](https://github.com/flytegg/mc-utils/assets/138625055/ca433e8b-1456-421a-aab6-ebee6b9fa06f)

### Extra Info

Heading back to spec savers

**Comment by StillLutto** [comment]
Didn't close because I only mentioned this issue in a comment. This should be closed.
